### ISSUE TITLE
Invalid user can log in

### ISSUE THREAD

**Issue by MFernstrom** [RapidInfoSys/Rapid#1]
You can log in with any username/password combination, no error pops up, but it does put you on a page with an Application box, and only one application visible.

**Comment by gareth-edwards** [comment]
Hi Marcus,

Thanks for your interest in Rapid and opening our first issue on GitHub!

I'm pleased you've got it running, and your feedback is very helpful.

The access and app you see with any username/password combination is because the app has a "public" security adapter so all authentication attempts pass. In future we plan to remove these from working with the login page as, I admit it's a little unhelpful.

**Comment by MFernstrom** [comment]
Rapid is pretty neat, so far I like it.

I kind of figured the reason was something like that, though I'd love to see maybe an Admin setting to list Live Sites / Login for the default page.

Getting it running was super easy, I just grabbed a jetty-runner, no problem at all.
